site_name: kustomizer
site_description: |
  An experimental package manager for distributing Kubernetes configuration as OCI artifacts.
site_author: Stefan Prodan
site_url: https://kustomizer.dev

repo_name: rawmind0/kustomizer
repo_url: https://github.com/rawmind0/kustomizer
edit_uri: ""

theme:
  name: material
  logo: images/favicon-round.png
  favicon: images/favicon-round.png
  language: en
  custom_dir: docs/theme/
  palette:
    primary: deep purple
    accent: indigo
  features:
    - navigation.sections

docs_dir: docs

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - codehilite
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Get Started: get-started.md
  - Install: install.md
  - GitHub Actions: github-actions.md
  - Guides:
      - Secure your Kubernetes supply chain with Kustomizer and Cosign: guides/secure-supply-chain.md
      - Encryption at rest with Kustomizer and Age: guides/artifacts-encryption.md
      - Deploy applications from Git with Kustomizer: guides/deploy-from-git.md
      - Continuous deployment with Kustomizer and Flux: guides/fluxcd.md
  - Command Reference:
      - Artifact:
          - Push: cmd/kustomizer_push_artifact.md
          - Tag: cmd/kustomizer_tag_artifact.md
          - Pull: cmd/kustomizer_pull_artifact.md
          - Diff: cmd/kustomizer_diff_artifact.md
          - Inspect: cmd/kustomizer_inspect_artifact.md
      - Inventory:
          - Apply: cmd/kustomizer_apply_inventory.md
          - Build: cmd/kustomizer_build_inventory.md
          - Diff: cmd/kustomizer_diff_inventory.md
          - Inspect: cmd/kustomizer_inspect_inventory.md
          - Get: cmd/kustomizer_get_inventory.md
          - Delete: cmd/kustomizer_delete_inventory.md
      - Config:
          - Init: cmd/kustomizer_config_init.md
          - View: cmd/kustomizer_config_view.md
      - Completion:
          - Bash: cmd/kustomizer_completion_bash.md
          - Fish: cmd/kustomizer_completion_fish.md
          - Powershell: cmd/kustomizer_completion_powershell.md
          - ZSH: cmd/kustomizer_completion_zsh.md
