name: docs

on:
  push:
    branches: [ 'docs*', 'main' ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
      options: --tty
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Generate cmd docs
        run: |
          go run ./cmd/kustomizer/ docgen
      - name: Run mkdocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: kustomizer.dev
          CONFIG_FILE: mkdocs.yml
