name: release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
      options: --tty
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: stefanaprodan
          password: ${{ secrets.PUSH_GITHUB_TOKEN }}
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0.17.7
      - name: Setup Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Write signing key to tmp
        run: echo "${{ secrets.COSIGN_KEY }}" > /tmp/cosign.key
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.PUSH_GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
